CREATE TABLE t1 (i INT, j INT);
CREATE TABLE t2 (k INT, j INT);
CREATE TABLE t3 (i3 INT, j3 INT);
INSERT INTO t1 VALUES(1, 1);
INSERT INTO t2 VALUES(1, 1);
SELECT * FROM t1 NATURAL JOIN t2;
SELECT * FROM t1 JOIN t2 USING (j);
SELECT * FROM t1 NATURAL LEFT JOIN t2;
